name: "Run CI"

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.9.1
          cache: true
      - run: pixi run doc
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'doc/build'
